PREFIX owl: <http://www.w3.org/2002/07/owl#> 
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> 
PREFIX ssn: <http://www.w3.org/ns/ssn/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> 
PREFIX sosa: <http://www.w3.org/ns/sosa/> 
PREFIX coswot: <https://coswot.gitlab.io/ontology/> 
PREFIX badataset: <http://example.org/coswot/buildingautomation#> 

SELECT ?prop
WHERE 
{
    badataset:Office429 coswot:hasProperty ?prop .
}